include_directories(.)
#add_subdirectory(Apache)
add_subdirectory(CORBA)
#add_subdirectory(Data)
add_subdirectory(Generics)
add_subdirectory(GeoIP)
add_subdirectory(HTTP)
#add_subdirectory(Language)
add_subdirectory(Logger)
#add_subdirectory(Oracle)
add_subdirectory(PlainStorage)
add_subdirectory(PrivacyFilter)
add_subdirectory(SNMP)
add_subdirectory(Stream)
add_subdirectory(String)
add_subdirectory(Sync)
add_subdirectory(UServer)

add_subdirectory(TestCommons)

add_subdirectory(UServerUtils)
