add_subdirectory(Allocator)
add_subdirectory(AllocatorsTest)
add_subdirectory(AppUtils)
add_subdirectory(BitAlgs)
add_subdirectory(BoundedMap)
add_subdirectory(CRC)
add_subdirectory(CompositeActiveObject)
add_subdirectory(CompressedSet)
add_subdirectory(CountryCodeManip)

add_subdirectory(Decimal)
add_subdirectory(Hash)
add_subdirectory(HashTable)
add_subdirectory(LastPtr)
add_subdirectory(Listener)
add_subdirectory(LocalInterfaces)
add_subdirectory(MTTester)
add_subdirectory(MemBuf)
add_subdirectory(Periodic)
add_subdirectory(Planner)
add_subdirectory(RandTest)
add_subdirectory(Reflection)
add_subdirectory(Scheduler)
add_subdirectory(Scheduler2)
add_subdirectory(Singleton)
add_subdirectory(SmartPtr)
add_subdirectory(TAlloc)
add_subdirectory(TaskRunner)
add_subdirectory(TaskRunnerPerf)
add_subdirectory(TaskRunnerQueue)
add_subdirectory(TaskRunnerSlowCoach)
add_subdirectory(TaskRunnerThreads)
add_subdirectory(TimeManipsTest)
add_subdirectory(Uuid)
