add_subdirectory(AsyncPoolComplexTest)
add_subdirectory(AsyncPoolSimpleTest)
add_subdirectory(AsynchVsSynch)
add_subdirectory(EmptyPoliciesInternalTest)
add_subdirectory(Expiration)
add_subdirectory(HTTPAddress)
add_subdirectory(HTTPCookie)
add_subdirectory(HttpTestCommons)
add_subdirectory(IDNA)
add_subdirectory(HttpJavaFunctions)
