services:
  oracle_build:
    image: oraclelinux:8.7
    container_name: unixcommons_cobrazz_build
    tty: true
    stdin_open: true

      
    working_dir: /app/ci
    command:
      - /bin/sh
      - -c
      - echo hello
