add_subdirectory(HTTP)

add_subdirectory(HostnameUtil)
add_subdirectory(GeoIP)
add_subdirectory(Generics)
add_subdirectory(CaseUtil)
add_subdirectory(CORBA)
add_subdirectory(Java)
add_subdirectory(ReferenceCounting)
add_subdirectory(Language)
add_subdirectory(Logger)
add_subdirectory(PlainStorage)
add_subdirectory(RotateLog)
add_subdirectory(PrivacyFilter)
add_subdirectory(SNMPAgent)
add_subdirectory(Stream)
add_subdirectory(String)
add_subdirectory(Sync)
add_subdirectory(TestCommons)
add_subdirectory(Profiler)
add_subdirectory(XMLUtility)
add_subdirectory(eh)
add_subdirectory(xsd)
