add_subdirectory(DynAny)
#add_subdirectory(Few_endpoints_tooling)
#add_subdirectory(GIOP_over_SSL)
#add_subdirectory(Keep-alive)
#add_subdirectory(OBV)
#add_subdirectory(POA)
#add_subdirectory(SSL_Dual)
#add_subdirectory(coORBs)
#add_subdirectory(custom_valuetype)
#add_subdirectory(narrow)
#add_subdirectory(one_way)
#add_subdirectory(persistent)
#add_subdirectory(thread-pool)
#add_subdirectory(timeout)
#add_subdirectory(timeout_cont)
