name: unixcommons_cobrazz_build

on:
  push:
    branches:
      - CI
  pull_request:
    branches:
      - CI

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up Docker Compose
        run: |
          sudo apt install docker-compose
          docker-compose --version
          

  
      - name: Making base cache
        working-directory: ci
        run: |
          if [ ! -d cache ]; then
            sudo mkdir cache
            docker run --name tmp_oracle oraclelinux:8.7

            sudo docker cp tmp_oracle:/usr ./cache/usr
            sudo docker cp tmp_oracle:/etc ./cache/etc
            sudo docker cp tmp_oracle:/var ./cache/var
            sudo docker cp tmp_oracle:/bin ./cache/bin
            sudo docker cp tmp_oracle:/lib ./cache/lib
            sudo docker cp tmp_oracle:/lib64 ./cache/lib64
            sudo docker cp tmp_oracle:/sbin ./cache/sbin
            sudo docker cp tmp_oracle:/opt ./cache/opt
            
            docker rm tmp_oracle
          else
            echo "cache folder presents. Skipping Docker cache creation."
          fi;
                                    
      - name: Сreate env
        run: | 
          docker-compose run oracle_env_creation;
          exit $?;
        working-directory: ci
      
      - name: Adjust permissions
        run: |
          sudo chmod -R o+rwx ./ci/cache
      
      - name: Save cache
        uses: actions/cache/save@v3
        with:
          path: |
           ./ci/cache
          key: cache-${{ runner.os }}-${{ github.run_id }}  
          restore-keys: cache-${{ runner.os }}-  
        
      - name: Restore build
        uses: actions/cache/restore@v3
        with:
          path: |
           ./ci/build
          key:  build-${{ runner.os }}-${{ github.run_id }}          
          restore-keys: build-${{ runner.os }}-
          
      - name: build
        working-directory: ci
        run: |
          docker-compose run build;
          exit $?;

      - name: Save build
        uses: actions/cache/save@v3
        if: always()
        with:
          path: |
           ./ci/build
          key: build-${{ runner.os }}-${{ github.run_id }}          
          restore-keys: build-${{ runner.os }}-
