name: unixcommons_cobrazz_build

on:
  push:
    branches:
      - CI
  pull_request:
    branches:
      - CI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up Docker Compose
        run: |
          sudo apt install docker-compose
          docker-compose --version
          
      - name: Making base cache
        run: |
          sudo mkdir cache
          if [ $? -eq 0 ]; then
            docker run --name tmp_oracle oraclelinux:8.7

            sudo docker cp tmp_oracle:/usr ./cache/usr
            sudo docker cp tmp_oracle:/etc ./cache/etc
            sudo docker cp tmp_oracle:/var ./cache/var
            sudo docker cp tmp_oracle:/bin ./cache/bin
            sudo docker cp tmp_oracle:/lib ./cache/lib
            sudo docker cp tmp_oracle:/lib64 ./cache/lib64
            sudo docker cp tmp_oracle:/sbin ./cache/sbin
            sudo docker cp tmp_oracle:/opt ./cache/opt
            
            docker rm tmp_oracle
          else
            echo "cache folder presents. Skipping Docker cache creation."
          fi
        working-directory: ci
        
      - name: Save cache
        uses: actions/cache@v3
        with:
          path: ci/cache
          key: ${{ runner.os }}-cache-${{ hashFiles('ci/docker-compose.yml') }}
          restore-keys: |
            ${{ runner.os }}-cache-
          
      - name: Build
        run: docker-compose up
        working-directory: ci
