name: unixcommons_cobrazz_build

on:
  push:
    branches:
      - CI
  pull_request:
    branches:
      - CI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
    
      - name: Set up Docker Compose
        run: |
          sudo apt install docker-compose
          docker-compose --version